---
name: Contextual Logger Test
on: [push, pull_request]
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7, '3.0', 3.1]
        gemfile:
        - Gemfile
        - gemfiles/rails_5.gemfile
        - gemfiles/rails_6.gemfile
        exclude:
        - ruby: '3.0'
          gemfile: gemfiles/rails_5.gemfile
        - ruby: 3.1
          gemfile: gemfiles/rails_5.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: 2.2.29
        bundler-cache: true
    - run: bundle exec rspec
